name: color-ref_comm

task: 
  name: LockTask

channel:
  name: GaussianChannel
  n_msg: 32
  std: 0.5

model: 
  name: RecurrentQModel
  n_hidden: 256
  communicate: true
  discount: 0.9
  #step_size: 0.003
  step_size: 0.0003

translator:
  name: BeliefTranslator

experiment:
  train: true
  translate: true

trainer:
  n_replay_episodes: 500
  n_batch_episodes: 256
  n_batch_history: 10
  n_timeout: 100
  good_fraction: 0.2
  n_iters: 100000
  n_update_iters: 100
