name: debug_lex

task: 
  name: ColorRefTask
  train: false
  lexicon: true

channel:
  name: GaussianChannel
  n_msg: 32
  std: 0.5

model: 
  name: RecurrentQModel
  n_hidden: 64
  communicate: true
  discount: 0.9
  step_size: 0.003
  load: debug

translator:
  name: GenBeliefTranslator
  n_hidden: 64
  step_size: 0.003
  #weight_by_z: false
  #condition_on_x: false

trainer:
  n_replay_episodes: 500
  n_batch_episodes: 256
  n_rollout_episodes: 1
  n_batch_history: 10
  n_timeout: 100
  good_fraction: 0.2
  n_iters: 100000
  n_update_iters: 100
  n_distractors: 1
