name: color-ref_comm

task: 
  name: ColorRefTask

channel:
  name: GaussianChannel
  n_msg: 8
  std: 0.5

model: 
  name: RecurrentQModel
  n_hidden: 100
  communicate: true
  discount: 0.9
  step_size: 0.0003

translator:
  name: BeliefTranslator

experiment:
  train: true
  translate: true

trainer:
  n_replay_episodes: 1000
  n_batch_episodes: 100
  n_batch_history: 10
  n_timeout: 100
  good_fraction: 0.2
  n_iters: 200
  n_update_iters: 100
