name: birds_eval

task: 
  name: BirdsRefTask
  train: false
  lexicon: true
  visualize: true
  calibrate: true
  evaluate: true
  turkify: true

channel:
  name: GaussianChannel
  normalize: true
  n_msg: 64
  std: 0.3

model: 
  name: RecurrentQModel
  n_hidden: 256
  n_embed: 64
  communicate: true
  discount: 0.9
  step_size: 0.003
  message_cost: 0.0
  feature_depth: 1
  load: birds_train

translator:
  name: GenBeliefTranslator
  n_hidden: 128
  step_size: 0.0003
  normalization: local

trainer:
  n_replay_episodes: 500
  n_batch_episodes: 256
  n_rollout_episodes: 1
  n_batch_history: 3
  n_timeout: 3
  good_fraction: 0.1
  n_iters: 10000
  n_desc_iters: 10000
  n_update_iters: 100
  n_distractors: 1
  resume: false

lexicographer:
  c_agent: 0
  l_agent: 1
  mode: belief

evaluator:
  simulate_l: false
  n_episodes: 200
