name: birds_eval

task: 
  name: BirdsRefTask
  train: false
  lexicon: false
  evaluate: true

channel:
  name: GaussianChannel
  normalize: true
  n_msg: 128
  std: 0.0

model: 
  name: RecurrentQModel
  n_hidden: 256
  n_embed: 64
  communicate: true
  discount: 0.9
  step_size: 0.003
  message_cost: 0.000
  load: birds_train

translator:
  name: GenBeliefTranslator
  n_hidden: 256
  step_size: 0.003
  normalization: local

trainer:
  n_replay_episodes: 500
  n_batch_episodes: 256
  n_rollout_episodes: 1
  n_batch_history: 10
  n_timeout: 3
  good_fraction: 0.2
  n_iters: 20000
  n_update_iters: 100
  n_distractors: 1
  resume: false

evaluator:
  code_agent: 0
  desc_agent: 1
