name: drive_train

task: 
  name: DriveTask
  train: true
  lexicon: false
  evaluate: false

channel:
  name: GaussianChannel
  n_msg: 64
  normalize: true
  std: 0.0

model: 
  name: RecurrentQModel
  n_hidden: 512
  n_embed: 64
  communicate: true
  discount: 0.9
  step_size: 0.003
  message_cost: 0
  load: drive_train

translator:
  name: GenBeliefTranslator
  n_hidden: 128
  step_size: 0.003
  normalization: global

trainer:
  n_replay_episodes: 500
  n_batch_episodes: 256
  n_rollout_episodes: 1
  n_batch_history: 10
  n_timeout: 20
  good_fraction: 0.1
  n_iters: 40000
  n_update_iters: 100
  n_distractors: 1
  resume: false
