name: drive_lex

task: 
  name: DriveTask
  train: false
  lexicon: true

channel:
  name: GaussianChannel
  n_msg: 32
  normalize: true
  std: 0.5

model: 
  name: RecurrentQModel
  n_hidden: 256
  communicate: true
  discount: 0.9
  step_size: 0.003
  message_cost: 0
  load: drive_train

translator:
  name: GenBeliefTranslator
  n_hidden: 128
  step_size: 0.003
  normalization: global

trainer:
  n_replay_episodes: 500
  n_batch_episodes: 256
  n_rollout_episodes: 1
  n_batch_history: 10
  n_timeout: 100
  good_fraction: 0.2
  n_iters: 100000
  n_update_iters: 100
  n_distractors: 1
